export const messages = {
  ru: {
    title: '*МАМКИН ТРЕЙДЕР*',
    home: {
      info:
        'Площадка для крипто <b>трейдинга</b>, официально признанная безопасной для вашего психического здоровья.',
      rules: {
        register: 'Регистрируетесь 💪',
        money: 'Получаете виртуальные $10,000 💰',
        success: 'Показываете всем, на что способны 💣',
      },
      facebook: 'Войти через Facebook',
      opensource:
        'Код в <a href="https://github.com/mamkin-trade"><b>открытом доступе</b></a>',
      privacy: 'Политика конфиденциальности',
    },
    loading: 'Загружается...',
    noResults: 'Нет результатов',
    search: 'Поиск',
    leaderboard: {
      title: 'Рейтинг',
      name: 'Имя',
      balance: 'Баланс',
    },
    tickers: {
      title: 'Тикеры',
      pair: 'Пара',
      change: 'Изменение',
      volume: 'Объем',
    },
    price: 'Цена',
    balance: {
      title: 'Баланс',
      currency: 'Валюта',
      overall: 'Общий баланс',
    },
    amount: 'Количество',
    all: 'Все',
    rowsPerPageText: 'Элементов на странице:',
    orders: {
      title: 'Ордеры',
      noOrdersYet: 'Еще нет ордеров',
      created: 'Создан',
      pair: 'Пара',
      side: 'Сторона',
      type: 'Тип',
      completed: 'Успешен',
      cancelled: 'Отменен',
      executed: 'Выполнен',
    },
    buy: 'Покупка',
    sell: 'Продажа',
    bool: {
      yes: 'Да',
      no: 'Нет',
    },
    market: 'Маркет',
    limit: 'Лимит',
  },
  en: {
    title: '*MAMKIN TRADE*',
    home: {
      info:
        'Cryptocurrency <b>trading</b> platform, officially declared to be safe for your mental health.',
      rules: {
        register: 'Login 💪',
        money: 'Get virtual $10,000 💰',
        success: "Show'em how it's done 💣",
      },
      facebook: 'Login with Facebook',
      opensource:
        'Fully <a href="https://github.com/mamkin-trade"><b>open source</b></a>',
      privacy: 'Privacy policy',
    },
    loading: 'Loading...',
    noResults: 'No results',
    search: 'Search',
    leaderboard: {
      title: 'Leaderboard',
      name: 'Name',
      balance: 'Balance',
    },
    tickers: {
      title: 'Tickers',
      pair: 'Pair',
      change: 'Change',
      volume: 'Volume',
    },
    price: 'Price',
    balance: {
      title: 'Balance',
      currency: 'Currency',
      overall: 'Total balance',
    },
    amount: 'Amount',
    all: 'All',
    rowsPerPageText: 'Rows per page:',
    orders: {
      title: 'Orders',
      noOrdersYet: 'No orders yet',
      created: 'Created',
      pair: 'Pair',
      side: 'Side',
      type: 'Type',
      completed: 'Completed',
      cancelled: 'Cancelled',
      executed: 'Executed',
    },
    buy: 'Buy',
    sell: 'Sell',
    bool: {
      yes: 'Yes',
      no: 'No',
    },
    market: 'Market',
    limit: 'Limit',
  },
}
