export const messages = {
  ru: {
    title: '*МАМКИН ТРЕЙДЕР*',
    shortTitle: '*МТ*',
    home: {
      info:
        'Площадка для крипто <b>трейдинга</b>, официально признанная безопасной для вашего психического здоровья',
      rules: {
        register: 'Регистрируетесь 💪',
        money: 'Получаете виртуальные $10,000 💰',
        success: 'Показываете всем, на что способны 💣',
      },
      facebook: 'Войти через Facebook',
      opensource:
        'Код в <a href="https://github.com/mamkin-trade"><b>открытом доступе</b></a>',
      privacy: 'Политика конфиденциальности',
    },
    loading: 'Загружается...',
    noResults: 'Нет результатов',
    search: 'Поиск',
    leaderboard: {
      title: 'Рейтинг',
      name: 'Имя',
      balance: 'Баланс',
    },
    tickers: {
      title: 'Тикеры',
      change: 'Изменение',
      volume: 'Объем',
    },
    pair: 'Пара',
    price: 'Цена',
    balance: {
      title: 'Баланс',
      currency: 'Валюта',
      overall: 'Общий баланс',
    },
    amount: 'Количество',
    all: 'Все',
    rowsPerPageText: 'Элементов на странице:',
    orders: {
      title: 'Ордеры',
      noOrdersYet: 'Еще нет ордеров',
      created: 'Создан',
      completed: 'Завершен',
      cancelled: 'Отменен',
      executed: 'Выполнен',
    },
    side: 'Сторона',
    type: 'Тип',
    buy: 'Покупка',
    sell: 'Продажа',
    bool: {
      yes: 'Да',
      no: 'Нет',
    },
    market: 'Маркет',
    limit: 'Лимит',
    orderForm: {
      title: 'Добавить ордер',
      submit: 'Добавить ордер',
      useAll: 'Использовать все',
      searchHint: 'Попробуйте BTC/USD/ETH',
    },
    available: 'Доступно',
    total: 'Всего',
    errors: {
      greaterThanZero: 'Должно быть больше нуля',
      insufficientFunds: 'Недостаточно средств',
      general: 'Что-то пошло не так',
      minimumOrderSize: 'Минимальный ордер {minimumOrderSize}',
      maximumOrderSize: 'Максимальный ордер {maximumOrderSize}',
      greaterThanMinimumPrice: 'Минимальная цена {minimumPrice}',
      lessThanMaximumPrice: 'Максимальная цена {maximumPrice}',
      facebook:
        'Не получилось зайти через Фейсбук, у вас верифицирован email на Фейсбуке?',
    },
    close: 'Закрыть',
    snackbar: {
      orderAdded: 'Ордер добавлен успешно',
      orderDeleted: 'Ордер успешно удален',
    },
    cancel: 'Отменить',
    pairTip: 'Попробуйте выбрать тикер',
  },
  en: {
    title: '*MAMKIN TRADE*',
    shortTitle: '*MT*',
    home: {
      info:
        'Cryptocurrency <b>trading</b> platform, officially declared to be safe for your mental health',
      rules: {
        register: 'Login 💪',
        money: 'Get virtual $10,000 💰',
        success: "Show'em how it's done 💣",
      },
      facebook: 'Login with Facebook',
      opensource:
        'Fully <a href="https://github.com/mamkin-trade"><b>open source</b></a>',
      privacy: 'Privacy policy',
    },
    loading: 'Loading...',
    noResults: 'No results',
    search: 'Search',
    leaderboard: {
      title: 'Leaderboard',
      name: 'Name',
      balance: 'Balance',
    },
    tickers: {
      title: 'Tickers',
      change: 'Change',
      volume: 'Volume',
    },
    pair: 'Pair',
    price: 'Price',
    balance: {
      title: 'Balance',
      currency: 'Currency',
      overall: 'Total balance',
    },
    amount: 'Amount',
    all: 'All',
    rowsPerPageText: 'Rows per page:',
    orders: {
      title: 'Orders',
      noOrdersYet: 'No orders yet',
      created: 'Created',
      completed: 'Completed',
      cancelled: 'Cancelled',
      executed: 'Executed',
    },
    side: 'Side',
    type: 'Type',
    buy: 'Buy',
    sell: 'Sell',
    bool: {
      yes: 'Yes',
      no: 'No',
    },
    market: 'Market',
    limit: 'Limit',
    orderForm: {
      title: 'Add order',
      submit: 'Add order',
      useAll: 'Use all',
      searchHint: 'Try BTC/USD/ETH',
    },
    available: 'Available',
    total: 'Total',
    errors: {
      greaterThanZero: 'Should be greater than zero',
      insufficientFunds: 'Insufficient funds',
      general: 'Something went wrong',
      minimumOrderSize: 'Minimum order is {minimumOrderSize}',
      maximumOrderSize: 'Maximum order is {maximumOrderSize}',
      greaterThanMinimumPrice: 'Minimum price {minimumPrice}',
      lessThanMaximumPrice: 'Maximum price is {maximumPrice}',
      facebook:
        'Could not sign in with Facebook, do you have a verified email on Facebook?',
    },
    close: 'Close',
    snackbar: {
      orderAdded: 'Order was added successfully',
      orderDeleted: 'Order was deleted successfully',
    },
    cancel: 'Cancel',
    pairTip: 'Try selecting a ticker',
  },
}
