export const messages = {
  ru: {
    title: '*МАМКИН ТРЕЙДЕР*',
    shortTitle: '*МТ*',
    home: {
      info:
        'Площадка для крипто <b>трейдинга</b>, официально признанная безопасной для вашего психического здоровья',
      rules: {
        register: 'Регистрируетесь 💪',
        money: 'Получаете виртуальные $10,000 💰',
        success: 'Показываете всем, на что способны 💣',
      },
      facebook: 'Войти через Фейсбук',
      google: 'Войти через Гугл',
      opensource:
        'Код в <a target="_blank" href="https://github.com/mamkin-trade"><b>открытом доступе</b></a>',
      privacy: 'Политика конфиденциальности',
    },
    loading: 'Загружается...',
    noResults: 'Нет результатов',
    search: 'Поиск',
    leaderboard: {
      title: 'Рейтинг',
      name: 'Имя',
      balance: 'Баланс',
    },
    tickers: {
      title: 'Тикеры',
      change: 'Изменение',
      volume: 'Объем',
      buy: 'Покупка',
      sell: 'Продажа',
      spread: 'Разница',
    },
    chart: {
      title: 'График'
    },
    pair: 'Пара',
    price: 'Цена',
    balance: {
      title: 'Баланс',
      currency: 'Валюта',
      overall: 'Общий баланс',
    },
    amount: 'Количество',
    all: 'Все',
    rowsPerPageText: 'Элементов на странице:',
    orders: {
      title: 'Ордеры',
      noOrdersYet: 'Еще нет ордеров',
      created: 'Создан',
      completed: 'Завершен',
      cancelled: 'Отменен',
      executed: 'Выполнен',
    },
    side: 'Сторона',
    type: 'Тип',
    buy: 'Покупка',
    sell: 'Продажа',
    bool: {
      yes: 'Да',
      no: 'Нет',
    },
    market: 'Маркет',
    limit: 'Лимит',
    orderForm: {
      title: 'Добавить ордер',
      submit: 'Добавить ордер',
      useAll: 'Использовать все',
      searchHint: 'Попробуйте BTC/USD/ETH',
    },
    available: 'Доступно',
    total: 'Всего',
    errors: {
      greaterThanZero: 'Должно быть больше нуля',
      insufficientFunds: 'Недостаточно средств',
      general: 'Что-то пошло не так',
      minimumOrderSize: 'Минимальный ордер {minimumOrderSize}',
      maximumOrderSize: 'Максимальный ордер {maximumOrderSize}',
      greaterThanMinimumPrice: 'Минимальная цена {minimumPrice}',
      lessThanMaximumPrice: 'Максимальная цена {maximumPrice}',
      facebook: 'Не получилось зайти через Фейсбук',
      telegram: 'Не получилось зайти через Телеграм',
      google: 'Не получилось зайти через Гугл',
    },
    close: 'Закрыть',
    snackbar: {
      orderAdded: 'Ордер добавлен успешно',
      orderDeleted: 'Ордер успешно удален',
    },
    cancel: 'Отменить',
    pairTip: 'Попробуйте выбрать тикер',
    support:
      'Вопросы? Присоединяйтесь к <a target="_blank" href="https://t.me/joinchat/BIlEBxNgY3QDF3bzmigJsQ">нашей Телеграм группе</a>',
    stats:
      'Пользователей: {userCount}, ордеров: {ordersCount}, торгуется: ${totalUSDTraded}',
    logout: 'Выйти',
    reset: 'Сброс',
    resetMessage:
      'Вы уверены, что хотите удалить все данные? Данные включают в себя ваши ордера и баланс. Я повторяю: вы начнете снова. Назад пути не будет. Вы начнете снова с $10 000 и пустой историей ордеров. Нажав на "Сброс", вы соглашаетесь потерять все.',
    resetSuccess: 'Сброс прошел успешно',
  },
  en: {
    title: '*MAMKIN TRADE*',
    shortTitle: '*MT*',
    home: {
      info:
        'Cryptocurrency <b>trading</b> platform, officially declared to be safe for your mental health',
      rules: {
        register: 'Login 💪',
        money: 'Get virtual $10,000 💰',
        success: "Show'em how it's done 💣",
      },
      facebook: 'Login with Facebook',
      google: 'Login with Google',
      opensource:
        'Fully <a target="_blank" href="https://github.com/mamkin-trade"><b>open source</b></a>',
      privacy: 'Privacy policy',
    },
    loading: 'Loading...',
    noResults: 'No results',
    search: 'Search',
    leaderboard: {
      title: 'Leaderboard',
      name: 'Name',
      balance: 'Balance',
    },
    tickers: {
      title: 'Tickers',
      change: 'Change',
      volume: 'Volume',
      buy: 'Buy',
      sell: 'Sell',
      spread: 'Spread',
    },
    chart: {
      title: 'Chart'
    },
    pair: 'Pair',
    price: 'Price',
    balance: {
      title: 'Balance',
      currency: 'Currency',
      overall: 'Total balance',
    },
    amount: 'Amount',
    all: 'All',
    rowsPerPageText: 'Rows per page:',
    orders: {
      title: 'Orders',
      noOrdersYet: 'No orders yet',
      created: 'Created',
      completed: 'Completed',
      cancelled: 'Cancelled',
      executed: 'Executed',
    },
    side: 'Side',
    type: 'Type',
    buy: 'Buy',
    sell: 'Sell',
    bool: {
      yes: 'Yes',
      no: 'No',
    },
    market: 'Market',
    limit: 'Limit',
    orderForm: {
      title: 'Add order',
      submit: 'Add order',
      useAll: 'Use all',
      searchHint: 'Try BTC/USD/ETH',
    },
    available: 'Available',
    total: 'Total',
    errors: {
      greaterThanZero: 'Should be greater than zero',
      insufficientFunds: 'Insufficient funds',
      general: 'Something went wrong',
      minimumOrderSize: 'Minimum order is {minimumOrderSize}',
      maximumOrderSize: 'Maximum order is {maximumOrderSize}',
      greaterThanMinimumPrice: 'Minimum price {minimumPrice}',
      lessThanMaximumPrice: 'Maximum price is {maximumPrice}',
      facebook: 'Could not sign in with Facebook',
      telegram: 'Could not sign in with Telegram',
      google: 'Could not sign in with Google',
    },
    close: 'Close',
    snackbar: {
      orderAdded: 'Order was added successfully',
      orderDeleted: 'Order was deleted successfully',
    },
    cancel: 'Cancel',
    pairTip: 'Try selecting a ticker',
    support:
      'Questions? Join <a target="_blank" href="https://t.me/joinchat/BIlEBxNgY3QDF3bzmigJsQ">our Telegram group</a>',
    stats:
      'Users: {userCount}, orders: {ordersCount}, traded: ${totalUSDTraded}',
    logout: 'Logout',
    reset: 'Reset',
    resetMessage:
      'Are you sure you want to delete all data? It includes your orders and balance. I repeat: you will start over. There will be no turning back. You will start again with $10 000 and no order history. By pressing the "Reset" button below you agree to loosing everything.',
    resetSuccess: 'Reset succeeded',
  },
}
